name = "somstrategies"
type = "javascript"
compatibility_date = "2024-01-01"

[env.production]
name = "somstrategies-prod"

[build]
command = ""
cwd = null
watch_paths = null

[build.upload]
format = "service-worker"
